# Add in your keys and tokens.
ACCESS_TOKEN = "1226663269-4GzfHKajP2FMyYEW5BiDwn0M8YobNRthwF6pFSL"
ACCESS_TOKEN_SECRET = "yv96lq8i2wQJm26dGNmOwXY90gYlrc2BqlzGzsWgQyiqZ"
CONSUMER_KEY = "qDFqHij8aY7QhkZ5jyfbFfBYp"
CONSUMER_KEY_SECRET = "VXMPQr2eXD8K2em9ctMvDh5ierWYcbiPtmmWsLRKTXj53mfC1g"

def getKeys():
    return (ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_KEY_SECRET)

